---
title: "more abundant features SMRW 11192024"
output: html_document
date: "2024-11-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/Marquis.Yazzie/OneDrive - University of Denver/Desktop/DU Research/SMRW project/abundant propogated structures SMRW")
```


```{r}
dset<-read.csv("All_SMRW_vs_NS_Averaged_technical_replicates_volcano_plot_with_significance_01252024.csv", header = TRUE)

summary<-read.csv("canopus_compound_summary.csv", header = TRUE)
```

```{r}
dset1<- subset(dset, Sample_Type == "Significant in SMRW")
```

```{r}
merged_df <- merge(dset1, summary, by.x = "featureIDs", by.y = "featureId", all.x = TRUE)

```

```{r}
num_unique_values <- length(unique(merged_df$NPC.class))
num_unique_values <- length(unique(merged_df$NPC.class))


id_frequencies <- table(merged_df$NPC.class)
print(id_frequencies)
id_frequencies_df <- as.data.frame(id_frequencies)
colnames(id_frequencies_df) <- c("NPC.class", "Frequency")

id_frequencies_superclass <-table(merged_df$NPC.pathway)
print(id_frequencies_superclass)
id_frequencies_superclass_df <- as.data.frame(id_frequencies_superclass)
colnames(id_frequencies_superclass_df) <- c("NPC.superclass", "Frequency")


  

```

```{r}

# Importing required library 
library(ggplot2) 
library(treemapify)
library(dplyr)
library(svglite)
library(stringr)
library(plotly)

```


```{r}
merged_df_summary_2 <- merged_df %>%
  filter(!is.na(NPC.class) & !is.na(NPC.pathway))

merged_df_summary <- merged_df %>%
  dplyr::count(NPC.class, NPC.pathway, name = "frequency")

merged_df_summary <- merged_df_summary[!is.na(merged_df_summary$NPC.class), ]

```



```{r}
merged_df_summary$NPC.class <- iconv(merged_df_summary$NPC.class, from = "latin1", to = "UTF-8", sub = "")

merged_df_summary_1 <- merged_df_summary[merged_df_summary$frequency > 3, ]

merged_df_summary_1$NPC.class <- str_trunc(merged_df_summary_1$NPC.class, width = 20)


treemap <- ggplot2::ggplot(merged_df_summary_1,aes(area=frequency,fill=NPC.pathway, 
                       label=NPC.class,subgroup=NPC.pathway))+ 
  treemapify::geom_treemap(layout="squarified")+ 
  geom_treemap_text(place = "centre", size =8)


plot(treemap)
ggplotly(treemap)


ggsave(file="more_abundant_compound_classes_SMRW_11192024.svg", plot=treemap, width=8, height=6)

```
