---
title: "combined_box_plot_10162024"
output: html_document
date: "2024-10-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(stringr)
library(data.table)
library(readr)
library(dplyr)
library(tidyr)
library(reshape)     
library(gplots)
library(pheatmap)
library(heatmap3)
library(magrittr) 
library(tibble) 
library(RColorBrewer)
library(paletteer)
library(clr)
library(tidyverse) #used for data science. The eight core packages inside this library are: ggplot2 (data visualisation), dplyr (data manipulation), tidyr, readr, purrr, tibble, stringr, and forcats
library(KODAMA) # to use the normalisation function
library(ggrepel) #mainly used to repel overlapping text labels in ggplots
library(vegan) #popular library for analysing ecological diversity and for multivariate analysis of community data. Here, we use it for PCoA
library(svglite) #to save the plots in support vector graphics (svg) format
library(factoextra) #for extracting and visualizing outputs of multivariate analyses such as PCA, k-means
library(ggsci) #provides color palettes for ggplot2 that can be used for scientific journals
library(matrixStats) #contains highly optimized functions to perform statistics on matrix data
library(cowplot) #efficient functions to arrange several plots

```

```{r}
setwd("C:/Users/Marquis.Yazzie/OneDrive - University of Denver/Desktop/Aron_Lab_Data/SMRW_vs_NS_project/Kruskal_wallis_with_Normalized_Peak_area_annotations/Averaged_technical_replicates_pos_mode_05252024")
```

## Load in Data

### Normalized quant file

```{r}
quant <- read.csv("average_technical_replicates_10292023.csv", header=T, check.names=F)

```

### Metadata

```{r}
md <- read.csv("average_technical_replicates_metadata_05222024.csv", header = T, check.names = F, sep = ',')
```

## Cleanup code

### Transpose the quant table

```{r}
quant <- t(quant)
quant <- as.data.frame(quant)

new_colnames <- as.character(quant[1, ])
quant <- quant[-1,]

colnames(quant) <- new_colnames

```

```{r}
numeric_columns <- sapply(quant, is.numeric)
numeric_columns

convert_to_numeric <- function(column) {
  as.numeric(as.character(column))
}

# Apply the function to all columns
quant <- quant %>% mutate_all(convert_to_numeric)
```

```{r}
quant <- quant %>% tibble::rownames_to_column("filename")

quant$filename <- gsub(" Peak height", "", quant$filename)

md <- md %>% filter(ATTRIBUTE_Sample_Type != "Pooled_QC")
md <- md %>% filter(ATTRIBUTE_Sample_Type != "Ext_Blank")

quant <- quant %>% filter(filename != "pooled_QC_1.mzML") %>% filter(filename != "mz") %>% filter(filename != "retention_time")
```

### Merge feature table and metadata for plotting

```{r}
data_merge <- md %>% dplyr::select("filename", "ATTRIBUTE_Sample_Type") %>% 
  left_join(quant, by = "filename")


```

### Set level to plot

```{r}
data_merge$ATTRIBUTE_Sample_Type <- factor(data_merge$ATTRIBUTE_Sample_Type, levels = c("Natural Snowfall", "Low Snowmaking","High Snowmaking"))
```



```{r}

my_data <- data_merge %>% select(filename, ATTRIBUTE_Sample_Type,`7369`, `10647`, `10817`, `2030`, `4014`, `5974`, `3233`, `2948`, `12950`, `11827`, `7667`, `7474`)

```

```{r}
my_data_2 <- my_data %>%
  pivot_longer(
    cols = c(`7369`, `10647`, `10817`, `2030`, `4014`, `5974`, `3233`, `2948`, `12950`, `11827`, `7667` , `7474`), # Specify the columns to reshape
    names_to = "Feature_ID",                  # New column for feature IDs
    values_to = "Normalized_Peak_Area"       # New column for the values
  )
```

```{r}
molecule_mapping <- c(
  `7369` = "Azithromycin",
  `10647` = "Azithromycin + aldehyde",
  `10817` = "Azithromycin - desoamine",
  `2030` = "Atenolol",
  `4014` = "Metropolol acid",
  `5974` = "Metropolol",
  `3233` = "mz 284.185",
  `2948` = "O-demethylmetropolol",
  `12950` = "Fexofenadine",
  `11827` = "Terfenadine",
  `7667` = "Venlafaxine",
  `7474` = "N-Desmethylvenlafaxine"
)

# Add the Molecule column using dplyr
my_data_2 <- my_data_2 %>%
  mutate(Molecule = molecule_mapping[Feature_ID])


```

```{r}
Azithromycin_family <- my_data_2 %>%
  filter(Molecule %in% c("Azithromycin", "Azithromycin + aldehyde", "Azithromycin - desoamine"))

Atenolol_family <- my_data_2 %>%
  filter(Molecule %in% c("Atenolol", "Metropolol", "Metropolol acid", "mz 284.185", "O-demethylmetropolol"))

Fexofenadine_family <- my_data_2 %>%
  filter(Molecule %in% c("Fexofenadine", "Terfenadine"))

Venlafaxine_family <- my_data_2 %>%
  filter(Molecule %in% c("Venlafaxine", "N-Desmethylvenlafaxine"))

```

```{r}
Atenolol_high_snowmaking <- Atenolol_family %>%
  filter(ATTRIBUTE_Sample_Type == "High Snowmaking")

kruskal_test <- kruskal.test(Normalized_Peak_Area ~ Molecule, data = Atenolol_high_snowmaking)
print(kruskal_test)
```

```{r}
Atenolol_family_plot <- ggplot(Atenolol_family, aes(x = factor(Molecule, levels = c("Atenolol", "Metropolol", "Metropolol acid", "mz 284.185", "O-demethylmetropolol")),
               y = Normalized_Peak_Area,
               fill = ATTRIBUTE_Sample_Type)) +
  geom_boxplot() +# Use 'position = dodge' for side-by-side bars
  labs(x = "", y = "Normalized Peak Area", fill = "Snowmaking Type") +
  theme_minimal() +
  scale_fill_manual(values = c("Natural Snowfall" = "#619CFF",
                               "Low Snowmaking" = "#00BA38",
                               "High Snowmaking" = "#F8766D" 
                               )) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=12), 
        axis.text.y = element_text(size = 12),  # Y-axis text size
    axis.title.y = element_text(size = 12),  # Y-axis title size
    legend.title = element_text(size = 12),  # Fill label title size
    legend.text = element_text(size = 12),   # Fill label text size
    panel.grid.major = element_blank(),      # Remove major gridlines
    panel.grid.minor = element_blank(),      # Remove minor gridlines
    panel.border = element_blank(),          # Remove panel border
    axis.line = element_line(size = 0.5, color = "black"))

Atenolol_family_plot

ggsave(file="Atenolol_family_abundance_01192025.svg", plot=Atenolol_family_plot, width=8, height=6)

```
```{r}
Atenolol_HS_family_plot <- ggplot(Atenolol_high_snowmaking, aes(x = factor(Molecule, levels = c("Atenolol", "Metropolol", "Metropolol acid", "mz 284.185", "O-demethylmetropolol")),
               y = Normalized_Peak_Area,
               fill = ATTRIBUTE_Sample_Type)) +
  geom_boxplot() +# Use 'position = dodge' for side-by-side bars
  labs(x = "", y = "Normalized Peak Area", fill = "Snowmaking Type") +
  theme_minimal() +
  scale_fill_manual(values = c("Natural Snowfall" = "#619CFF",
                               "Low Snowmaking" = "#00BA38",
                               "High Snowmaking" = "#F8766D" 
                               )) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=12), 
        axis.text.y = element_text(size = 12),  # Y-axis text size
    axis.title.y = element_text(size = 12),  # Y-axis title size
    legend.title = element_text(size = 12),  # Fill label title size
    legend.text = element_text(size = 12),   # Fill label text size
    panel.grid.major = element_blank(),      # Remove major gridlines
    panel.grid.minor = element_blank(),      # Remove minor gridlines
    panel.border = element_blank(),          # Remove panel border
    axis.line = element_line(size = 0.5, color = "black"))

Atenolol_HS_family_plot

ggsave(file="Atenolol_HS_family_abundance_01192025.svg", plot=Atenolol_HS_family_plot, width=8, height=6)
```



```{r}
Azithromycin_high_snowmaking <- Azithromycin_family %>%
  filter(ATTRIBUTE_Sample_Type == "High Snowmaking")

kruskal_test <- kruskal.test(Normalized_Peak_Area ~ Molecule, data = Azithromycin_high_snowmaking)
print(kruskal_test)
```


```{r}
qq_plot <- Azithromycin_high_snowmaking %>%
  ggplot(aes(sample = Normalized_Peak_Area)) +
  stat_qq() +
  stat_qq_line() +
  facet_wrap(~ Molecule, scales = "free") +
  labs(
    title = "Q-Q Plots for Each Molecule",
    x = "Theoretical Quantiles",
    y = "Sample Quantiles"
  ) +
  theme_minimal()

qq_plot
```

```{r}
# Install and load dunn.test package if not already installed
if (!requireNamespace("dunn.test", quietly = TRUE)) {
  install.packages("dunn.test")
}
library(dunn.test)

# Dunn's test
dunn_test <- dunn.test(
  x = Azithromycin_high_snowmaking$Normalized_Peak_Area,
  g = Azithromycin_high_snowmaking$Molecule,
  method = "bonferroni"
)
print(dunn_test)
```


```{r}

Azithromycin_HS_family_plot <- ggplot(Azithromycin_high_snowmaking, aes(x = factor(Molecule, levels = c("Azithromycin", "Azithromycin + aldehyde", "Azithromycin - desoamine")),
               y = Normalized_Peak_Area,
               fill = ATTRIBUTE_Sample_Type)) +
  geom_boxplot() +# Use 'position = dodge' for side-by-side bars
  labs(x = "", y = "Normalized Peak Area", fill = "Snowmaking Type") +
  theme_minimal() +
  scale_fill_manual(values = c("Natural Snowfall" = "#619CFF",
                               "Low Snowmaking" = "#00BA38",
                               "High Snowmaking" = "#F8766D" 
                               )) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=12), 
        axis.text.y = element_text(size = 12),  # Y-axis text size
    axis.title.y = element_text(size = 12),  # Y-axis title size
    legend.title = element_text(size = 12),  # Fill label title size
    legend.text = element_text(size = 12),   # Fill label text size
    panel.grid.major = element_blank(),      # Remove major gridlines
    panel.grid.minor = element_blank(),      # Remove minor gridlines
    panel.border = element_blank(),          # Remove panel border
    axis.line = element_line(size = 0.5, color = "black"))

Azithromycin_HS_family_plot

ggsave(file="Azithromycin_HS_family_abundance_01192025.svg", plot=Azithromycin_HS_family_plot, width=8, height=6)
```



```{r}
install.packages("ggsignif")
library(ggsignif)


# Example of adding significance to your plot
Azithromycin_HS_family_plot <- Azithromycin_HS_family_plot +
  geom_signif(
    comparisons = list(c("Azithromycin", "Azithromycin + aldehyde"), c("Azithromycin", "Azithromycin - desoamine")),
    map_signif_level = TRUE, 
    step_increase = 0.1
  )

Azithromycin_HS_family_plot

# Save the updated plot
ggsave(file = "Azithromycin_family_abundance_with_significance.svg", plot = Azithromycin_HS_family_plot, width = 8, height = 6)


```


```{r}
Azithromycin_family_plot <- ggplot(Azithromycin_family, aes(x = factor(Molecule, levels = c("Azithromycin", "Azithromycin + aldehyde", "Azithromycin - desoamine")),
               y = Normalized_Peak_Area,
               fill = ATTRIBUTE_Sample_Type)) +
  geom_boxplot() +# Use 'position = dodge' for side-by-side bars
  labs(x = "", y = "Normalized Peak Area", fill = "Snowmaking Type") +
  theme_minimal() +
  scale_fill_manual(values = c("Natural Snowfall" = "#619CFF",
                               "Low Snowmaking" = "#00BA38",
                               "High Snowmaking" = "#F8766D" 
                               )) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=12), 
        axis.text.y = element_text(size = 12),  # Y-axis text size
    axis.title.y = element_text(size = 12),  # Y-axis title size
    legend.title = element_text(size = 12),  # Fill label title size
    legend.text = element_text(size = 12),   # Fill label text size
    panel.grid.major = element_blank(),      # Remove major gridlines
    panel.grid.minor = element_blank(),      # Remove minor gridlines
    panel.border = element_blank(),          # Remove panel border
    axis.line = element_line(size = 0.5, color = "black"))

Azithromycin_family_plot

ggsave(file="Azithromycin_family_abundance_01192025.svg", plot=Azithromycin_family_plot, width=8, height=6)
```



```{r}
# Example of adding significance to your plot
Azithromycin_family_plot <- Azithromycin_family_plot +
  geom_signif(
    comparisons = list(c("Azithromycin", "Azithromycin + aldehyde"), c("Azithromycin", "Azithromycin - desoamine")),
    map_signif_level = TRUE, 
    step_increase = 0.1
  )

Azithromycin_family_plot

# Save the updated plot
ggsave(file = "Azithromycin_family_abundance_with_significance.svg", plot = Azithromycin_HS_family_plot, width = 8, height = 6)
```


```{r}
Fexofenadine_high_snowmaking <- Fexofenadine_family %>%
  filter(ATTRIBUTE_Sample_Type == "High Snowmaking")

kruskal_test_3 <- kruskal.test(Normalized_Peak_Area ~ Molecule, data = Fexofenadine_high_snowmaking)
print(kruskal_test_3)


mann_whitney_test_1 <- wilcox.test(Normalized_Peak_Area ~ Molecule, data = Fexofenadine_high_snowmaking)
print(mann_whitney_test_1)
```
```{r}
Fexofenadine_HS_family_plot <- ggplot(Fexofenadine_high_snowmaking, aes(x = factor(Molecule, levels = c("Fexofenadine", "Terfenadine")),
               y = Normalized_Peak_Area,
               fill = ATTRIBUTE_Sample_Type)) +
  geom_boxplot() +# Use 'position = dodge' for side-by-side bars
  labs(x = "", y = "Normalized Peak Area", fill = "Snowmaking Type") +
  theme_minimal() +
  scale_fill_manual(values = c("Natural Snowfall" = "#619CFF",
                               "Low Snowmaking" = "#00BA38",
                               "High Snowmaking" = "#F8766D" 
                               )) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=12), 
        axis.text.y = element_text(size = 12),  # Y-axis text size
    axis.title.y = element_text(size = 12),  # Y-axis title size
    legend.title = element_text(size = 12),  # Fill label title size
    legend.text = element_text(size = 12),   # Fill label text size
    panel.grid.major = element_blank(),      # Remove major gridlines
    panel.grid.minor = element_blank(),      # Remove minor gridlines
    panel.border = element_blank(),          # Remove panel border
    axis.line = element_line(size = 0.5, color = "black"))

Fexofenadine_HS_family_plot

ggsave(file="Fexofenadine_HS_family_abundance_01192025.svg", plot=Fexofenadine_HS_family_plot, width=8, height=6)
```


```{r}
Fexofenadine_family_plot <- ggplot(Fexofenadine_family, aes(x = factor(Molecule, levels = c("Fexofenadine", "Terfenadine")),
               y = Normalized_Peak_Area,
               fill = ATTRIBUTE_Sample_Type)) +
  geom_boxplot() +# Use 'position = dodge' for side-by-side bars
  labs(x = "", y = "Normalized Peak Area", fill = "Snowmaking Type") +
  theme_minimal() +
  scale_fill_manual(values = c("Natural Snowfall" = "#619CFF",
                               "Low Snowmaking" = "#00BA38",
                               "High Snowmaking" = "#F8766D" 
                               )) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=12), 
        axis.text.y = element_text(size = 12),  # Y-axis text size
    axis.title.y = element_text(size = 12),  # Y-axis title size
    legend.title = element_text(size = 12),  # Fill label title size
    legend.text = element_text(size = 12),   # Fill label text size
    panel.grid.major = element_blank(),      # Remove major gridlines
    panel.grid.minor = element_blank(),      # Remove minor gridlines
    panel.border = element_blank(),          # Remove panel border
    axis.line = element_line(size = 0.5, color = "black"))

Fexofenadine_family_plot

ggsave(file="Fexofenadine_family_abundance_01192025.svg", plot=Fexofenadine_family_plot, width=8, height=6)
```
```{r}
Venlafaxine_family_plot <- ggplot(Venlafaxine_family, aes(x = factor(Molecule, levels = c("Venlafaxine", "N-Desmethylvenlafaxine")),
               y = Normalized_Peak_Area,
               fill = ATTRIBUTE_Sample_Type)) +
  geom_boxplot() +# Use 'position = dodge' for side-by-side bars
  labs(x = "", y = "Normalized Peak Area", fill = "Snowmaking Type") +
  theme_minimal() +
  scale_fill_manual(values = c("Natural Snowfall" = "#619CFF",
                               "Low Snowmaking" = "#00BA38",
                               "High Snowmaking" = "#F8766D" 
                               )) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=12), 
        axis.text.y = element_text(size = 12),  # Y-axis text size
    axis.title.y = element_text(size = 12),  # Y-axis title size
    legend.title = element_text(size = 12),  # Fill label title size
    legend.text = element_text(size = 12),   # Fill label text size
    panel.grid.major = element_blank(),      # Remove major gridlines
    panel.grid.minor = element_blank(),      # Remove minor gridlines
    panel.border = element_blank(),          # Remove panel border
    axis.line = element_line(size = 0.5, color = "black"))

Venlafaxine_family_plot

ggsave(file="Fexofenadine_family_abundance_01192025.svg", plot=Fexofenadine_family_plot, width=8, height=6)
```

```{r}
Venlafaxine_high_snowmaking <- Venlafaxine_family %>%
  filter(ATTRIBUTE_Sample_Type == "High Snowmaking")

mann_whitney_test <- wilcox.test(Normalized_Peak_Area ~ Molecule, data = Venlafaxine_high_snowmaking)
print(mann_whitney_test)

unique(Venlafaxine_high_snowmaking$Molecule)

```

