---
title: "pharmceutical heatmap 11 3 2024"
author: "Marquis Y"
date: "2024-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("C:/Users/Marquis.Yazzie/OneDrive - University of Denver/Desktop/DU Research/SMRW project/pharmaceutical_heatmap_11032024/neg_heatmap_all_annotations")
```

```{r}
library(ggplot2)
library(stringr)
library(data.table)
library(readr)
library(dplyr)
library(tidyr)
library(reshape)     
library(gplots)
library(pheatmap)
library(heatmap3)
library(magrittr) 
library(tibble) 
library(RColorBrewer)
library(paletteer)
library(clr)
library(tidyverse) #used for data science. The eight core packages inside this library are: ggplot2 (data visualisation), dplyr (data manipulation), tidyr, readr, purrr, tibble, stringr, and forcats
library(KODAMA) # to use the normalisation function
library(ggrepel) #mainly used to repel overlapping text labels in ggplots
library(vegan) #popular library for analysing ecological diversity and for multivariate analysis of community data. Here, we use it for PCoA
library(svglite) #to save the plots in support vector graphics (svg) format
library(factoextra) #for extracting and visualizing outputs of multivariate analyses such as PCA, k-means
library(ggsci) #provides color palettes for ggplot2 that can be used for scientific journals
library(matrixStats) #contains highly optimized functions to perform statistics on matrix data
library(cowplot) #efficient functions to arrange several plots
```

```{r}
clustered <- read.csv("mzmine3_10162023_neg_CLR_Scaled_SMRW_vs_NS.csv", header=T, check.names=F)
```


```{r}

colnames(clustered)[1] <- "temp_row_name"  # Assign a temporary name to the first column
rownames(clustered) <- clustered$temp_row_name    # Set the first column as row names
clustered_1 <- as.data.frame(clustered)
clustered_1 <- clustered_1[, -1] 

clustered_1 <- clustered_1[rownames(clustered_1) != "pooled_QC_1.mzML", ]


```

```{r}
clustered_2 <- as.data.frame(clustered_1)

clustered_2 <- clustered_2 %>%
  select(starts_with("7242_"),starts_with("39012_"), starts_with("22501_"), starts_with("11300_"), starts_with("22186_"), starts_with("11786_"), starts_with("12440_"), starts_with("13047_"), starts_with("5925_"), starts_with("13237_"), starts_with("12415_"), starts_with("6102_"), starts_with("16526_"), starts_with("14593_"), starts_with("25698_"), starts_with("14278_"), starts_with("13389_"), starts_with("7021_"), starts_with("5075_"),starts_with("17305_"),starts_with("17046_"))
```


```{r}
clustered_3 <- as.data.frame(clustered_2)

clustered_3 <- clustered_3 %>%
   rename_with(~ str_replace(., "^7242_.*", "Esculetin")) %>%
  rename_with(~ str_replace(., "^39012_.*", "Docusate")) %>%
  rename_with(~ str_replace(., "^22501_.*", "Masoprocol")) %>%
  rename_with(~ str_replace(., "^11300_.*", "Polydatin")) %>%
    rename_with(~ str_replace(., "^22186_.*", "Xanthohumol")) %>%
  rename_with(~ str_replace(., "^11786_.*", "Isoquercetin")) %>%
  rename_with(~ str_replace(., "^12440_.*", "Luteolin")) %>%
  rename_with(~ str_replace(., "^13047_.*", "Caffeic Acid")) %>%
  rename_with(~ str_replace(., "^5925_.*", "Ensulizole")) %>%
  rename_with(~ str_replace(., "^13237_.*", "Quercetin")) %>%
  rename_with(~ str_replace(., "^12415_.*", "Cianidanol")) %>%
  rename_with(~ str_replace(., "^6102_.*", "Chlorothiazide")) %>%
  rename_with(~ str_replace(., "^16526_.*", "Valsartan Acid")) %>%
  rename_with(~ str_replace(., "^14593_.*", "Methylparaben")) %>%
  rename_with(~ str_replace(., "^25698_.*", "2,4-dinitrophenol")) %>%
  rename_with(~ str_replace(., "^14278_.*", "Azelaic Acid")) %>%
  rename_with(~ str_replace(., "^13389_.*", "Mandelic Acid")) %>%
  rename_with(~ str_replace(., "^7021_.*", "Glucose")) %>%
  rename_with(~ str_replace(., "^5075_.*", "Esculin")) %>%
  rename_with(~ str_replace(., "^17305_.*", "Hydrocortisone"))%>%
  rename_with(~ str_replace(., "^17046_.*", "Hymecromone analog (m/z -22)"))

```

```{r}
rownames(clustered_3)[rownames(clustered_3) == "A1.mzML"] <- "High Snowmaking 1"
rownames(clustered_3)[rownames(clustered_3) == "A2.mzML"] <- "High Snowmaking 2"
rownames(clustered_3)[rownames(clustered_3) == "A3.mzML"] <- "High Snowmaking 3"
rownames(clustered_3)[rownames(clustered_3) == "A4.mzML"] <- "High Snowmaking 4"
rownames(clustered_3)[rownames(clustered_3) == "A5.mzML"] <- "High Snowmaking 5"
rownames(clustered_3)[rownames(clustered_3) == "A6.mzML"] <- "High Snowmaking 6"
rownames(clustered_3)[rownames(clustered_3) == "A7.mzML"] <- "Low Snowmaking 1"
rownames(clustered_3)[rownames(clustered_3) == "A8.mzML"] <- "Low Snowmaking 2"
rownames(clustered_3)[rownames(clustered_3) == "A9.mzML"] <- "Low Snowmaking 3"
rownames(clustered_3)[rownames(clustered_3) == "A10.mzML"] <- "Natural Snowfall 1"
rownames(clustered_3)[rownames(clustered_3) == "A11.mzML"] <- "Natural Snowfall 2"
rownames(clustered_3)[rownames(clustered_3) == "A12.mzML"] <- "Natural Snowfall 3"
rownames(clustered_3)[rownames(clustered_3) == "A13.mzML"] <- "Natural Snowfall 4"
rownames(clustered_3)[rownames(clustered_3) == "A14.mzML"] <- "Natural Snowfall 5"
rownames(clustered_3)[rownames(clustered_3) == "A15.mzML"] <- "Natural Snowfall 6"
```


```{r}


clustered_3_matrix <- as.matrix(clustered_3)
clustered_3_matrix <- t(clustered_3_matrix)

par(mar = c(8, 8, 10, 10))  # Increase margins as needed

svg("heatmap_plot.svg", width = 10, height = 10)  # Adjust width and height as needed
heatmap.2(clustered_3_matrix, 
          scale = "row",        # Scale columns as in your example
          col = bluered(100),   # Choose a color palette, e.g., blue to red with 100 shades
          trace = "none",       # Remove trace lines for a cleaner look
          key = TRUE,           # Add color legend (color key)
          key.title = "Legend", # Title for the legend
          key.xlab = "Value",   # X-axis label for the legend
          dendrogram = "both",  # Display both row and column dendrograms
          density.info = "none", # Remove density plot
margins = c(10, 10), 
lhei = c(2, 12))
dev.off()

```

```{r}

svg("heatmap_plot_02172025.svg", width = 10, height = 10)
pheatmap(clustered_3_matrix, 
         scale = "row", 
         fontsize_row = 14, 
         fontsize_col = 14)
dev.off()
```

