---
title: "08092024_M_Meso_metallophore_discovery"
output: pdf_document
date: "2024-07-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set working drive

```{r}
setwd("C:/Users/Marquis.Yazzie/OneDrive - University of Denver/Desktop/DU Research/SMRW project/comparision to pendergraft features 11182024")
```

## Load in neccesary packages

```{r}
library(ggplot2)
library(stringr)
library(data.table)
library(readr)
library(dplyr)
library(tidyr)
library(reshape)     
library(gplots)
library(pheatmap)
library(heatmap3)
library(magrittr) 
library(tibble) 
library(RColorBrewer)
library(paletteer)
library(clr)
library(tidyverse) #used for data science. The eight core packages inside this library are: ggplot2 (data visualisation), dplyr (data manipulation), tidyr, readr, purrr, tibble, stringr, and forcats
library(KODAMA) # to use the normalisation function
library(ggrepel) #mainly used to repel overlapping text labels in ggplots
library(vegan) #popular library for analysing ecological diversity and for multivariate analysis of community data. Here, we use it for PCoA
library(svglite) #to save the plots in support vector graphics (svg) format
library(factoextra) #for extracting and visualizing outputs of multivariate analyses such as PCA, k-means
library(ggsci) #provides color palettes for ggplot2 that can be used for scientific journals
library(matrixStats) #contains highly optimized functions to perform statistics on matrix data
library(cowplot) #efficient functions to arrange several plots
```

### Normalized quant file

```{r}
quant <- read.csv("IB-Spray-DOM_MZmine237-17-7-Kai_IIN_GNPS_merged2_quant.csv", header=T, check.names=F)

selected_features <- subset(quant, `row ID` %in% c(34135, 52559, 120364, 38485))

```

### Metadata

```{r}
md <- read.csv("pendergraft_metadata_11182024.csv", header = T, check.names = F, sep = ',')
```

## Cleanup code

### Transpose the quant table

```{r}
selected_features <- t(selected_features)
selected_features <- as.data.frame(selected_features)

colnames(selected_features) <- selected_features["row ID", ]


```

```{r}
numeric_columns <- sapply(selected_features, is.numeric)
numeric_columns

convert_to_numeric <- function(column) {
  as.numeric(as.character(column))
}

# Apply the function to all columns
selected_features <- selected_features %>% mutate_all(convert_to_numeric)
```

```{r}
selected_features <- selected_features %>% tibble::rownames_to_column("filename")

selected_features$filename <- gsub(" Peak area", "", selected_features$filename)
```

### Merge feature table and metadata for plotting

```{r}
data_merge <- md %>% dplyr::select("filename", "Sample_name") %>% 
  left_join(selected_features, by = "filename")

data_merge <- md %>% dplyr::select("filename", "Sample_Type") %>% 
  left_join(data_merge, by = "filename")


```

### Subset media blank and extraction blank

```{r}
data_merge <- data_merge %>% filter(Sample_Type != "QC")



```

```{r}
colnames(data_merge)
```

```{r}

shared_feature_34135 <- data_merge %>%
  ggplot( aes(x= Sample_name, y= ` 34135`)) +
  geom_boxplot() +
  theme_classic() + 
  scale_y_log10()+
  labs(y= "Peak Area (AU)", x= expression(paste("")), shape ="")+
  theme(axis.title.x = element_text(family = "sans", size = 16, hjust = 0.5),  
        axis.title.y = element_text(family = "sans", size = 16, hjust = 0.5),  
        axis.text.x = element_text(family = "sans", size = 16, color = "black", angle = 45, hjust =1), 
        axis.text.y = element_text(family = "sans", size = 16, color= "black"),
        axis.line=element_line(size =1),
        axis.ticks=element_line(size=1), 
        axis.ticks.length=unit(.25, "cm"),
        legend.text=element_text(size=14,family="sans"))

plot(shared_feature_34135)
ggsave(file="shared_feature_34135.svg", plot=shared_feature_34135, width =9, height = 7 )
```

```{r}
shared_feature_120364 <- data_merge %>%
  ggplot( aes(x= Sample_name, y= `120364`)) +
  geom_boxplot() +
  theme_classic() + 
  scale_y_log10()+
  labs(y= "Peak Area (AU)", x= expression(paste("")), shape ="")+
  theme(axis.title.x = element_text(family = "sans", size = 16, hjust = 0.5),  
        axis.title.y = element_text(family = "sans", size = 16, hjust = 0.5),  
        axis.text.x = element_text(family = "sans", size = 16, color = "black", angle = 45, hjust =1), 
        axis.text.y = element_text(family = "sans", size = 16, color= "black"),
        axis.line=element_line(size =1),
        axis.ticks=element_line(size=1), 
        axis.ticks.length=unit(.25, "cm"),
        legend.text=element_text(size=14,family="sans"))

plot(shared_feature_120364)
ggsave(file="shared_feature_120364.svg", plot=shared_feature_120364, width =9, height = 7 )

```

```{r}
shared_feature_52559 <- data_merge %>%
  ggplot( aes(x= Sample_name, y= ` 52559`)) +
  geom_boxplot() +
  theme_classic() +
    scale_y_log10()+
  labs(y= "Peak Area (AU)", x= expression(paste("")), shape ="")+
  theme(axis.title.x = element_text(family = "sans", size = 16, hjust = 0.5),  
        axis.title.y = element_text(family = "sans", size = 16, hjust = 0.5),  
        axis.text.x = element_text(family = "sans", size = 16, color = "black", angle = 45, hjust =1), 
        axis.text.y = element_text(family = "sans", size = 16, color= "black"),
        axis.line=element_line(size =1),
        axis.ticks=element_line(size=1), 
        axis.ticks.length=unit(.25, "cm"),
        legend.text=element_text(size=14,family="sans"))

plot(shared_feature_52559)
ggsave(file="shared_feature_52559.svg", plot=shared_feature_52559, width =9, height = 7 )

```
