---
title: "combined_box_plot_10162024"
output: html_document
date: "2024-10-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library("ggpubr")
library("dplyr")
library("tidyverse")
library("readr")
library(ggplot2)
library(dunn.test)

```

```{r}
setwd("C:/Users/Marquis.Yazzie/OneDrive - University of Denver/Desktop/DU Research/SMRW project/Targeted analysis of SMRW and NS/SMRW_PRM_Pharma_retry_06102024")
```

```{r}
my_data2 <- read.csv("concentration table of molecule SMRW_ PRM 0614 2024.csv", header=T, check.names=F)

all_numeric <- all(sapply(my_data2$Normalized_peak_area, is.numeric))

my_data2 <- my_data2[, 1:6]

```


```{r}
my_data2 <-filter(my_data2, `Snow Type` !=  "Extraction Blank")


my_data<- my_data2 %>%
  filter(Molecule %in% c("Carbamazepine", "Fexofenadine", "Flecainide", "Fluconazole", "Lamotrigine"))

my_data$`Snow Type` <- factor(my_data$`Snow Type`, levels = c("Natural Snowfall", "Low Snowmaking", "High Snowmaking"))



```


```{r}
abundance <- ggplot(my_data, aes(x = factor(Molecule, levels = c("Carbamazepine", "Fexofenadine", "Flecainide","Fluconazole", "Lamotrigine")),
               y = `Concentration (ng/L)`,
               fill = `Snow Type`)) +
  geom_boxplot() +# Use 'position = dodge' for side-by-side bars
   geom_point(aes(color = `Snow Type`), position = position_dodge(width = 0.75), size = 2, alpha = 0.8) +
  labs(x = "", y = "Concentration (ng/L)", fill = "Snowmaking Type") +
  theme_minimal() +
  scale_fill_manual(values = c("Natural Snowfall" = "#619CFF",
                               "Low Snowmaking" = "#00BA38",
                               "High Snowmaking" = "#F8766D" 
                               )) +
  scale_color_manual(values = c("Natural Snowfall" = "#619CFF",
                                "Low Snowmaking" = "#00BA38",
                                "High Snowmaking" = "#F8766D")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=12), 
        axis.text.y = element_text(size = 12),  # Y-axis text size
    axis.title.y = element_text(size = 12),  # Y-axis title size
    legend.title = element_text(size = 12),  # Fill label title size
    legend.text = element_text(size = 12),   # Fill label text size
    panel.grid.major = element_blank(),      # Remove major gridlines
    panel.grid.minor = element_blank(),      # Remove minor gridlines
    panel.border = element_blank(),          # Remove panel border
    axis.line = element_line(size = 0.5, color = "black"))

abundance

ggsave(file="pharmaceutical_concentration_2_01182025.svg", plot=abundance, width=8, height=6)

```
