---
title: "volcano plot with annotations"
author: "Marquis Y"
date: "2025-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/Marquis.Yazzie/OneDrive - University of Denver/Desktop/Aron_Lab_Data/SMRW_vs_NS_project/Volcano_plot_SMRW_vs_NS_neg_mode")
```


```{r}
#read in libraries
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(broom)
library(AICcmodavg)
library(dplyr)
```

```{r}
data <-read.csv("All_SMRW_vs_NS_volcano_plot_with_significance_12172024.csv", header = TRUE)

```

```{r}
# Biostatsquid theme
theme_set(theme_classic(base_size = 20) +
            theme(
              axis.title.y = element_text(face = "bold", margin = margin(0,20,0,0), size = rel(1.1), color = 'black'),
              axis.title.x = element_text(hjust = 0.5, face = "bold", margin = margin(20,0,0,0), size = rel(1.1), color = 'black'),
              plot.title = element_text(hjust = 0.5)
            ))


data$Compound_Class[data$Compound_Class == ""] <- NA



data$Molecule <- iconv(data$Molecule, from = "latin1", to = "UTF-8", sub = "byte")

library(dplyr)

# Replace NA values in Compound_name where Compound_type is NA
data <- data %>%
  mutate(Molecule = ifelse(is.na(Compound_Class), "", Molecule))

unique(data$Compound_Class)

myvolcano2 <- ggplot(data = data, aes(x = logFC, y = -log10(pvalue))) +
  geom_vline(xintercept = c(-0.6, 0.6), col = "gray", linetype = 'dashed') +
  geom_hline(yintercept = -log10(0.05), col = "gray", linetype = 'dashed') +
  geom_point(aes(color = Compound_Class, shape = Sample_Type), size = 1.5, alpha = 0.8) +
  geom_text(aes(label = Molecule), size = 3, vjust = -0.5) +  # Add labels with Compound_name
  scale_color_manual(
    values = c("red", "blue"),  # Only define colors for non-NA values
    na.translate = FALSE  # Exclude NA values from the color mapping and legend
  ) +
  scale_shape_manual(
    values = c(0, 1, 2)  # Use hollow shapes for Sample_Type
  ) +
  coord_cartesian(ylim = c(0, 5), xlim = c(-15, 15)) +
  labs(color = 'Compound Type', shape = 'Significance') +
  scale_x_continuous(breaks = seq(-15, 15, 5)) +
  theme(
    plot.title = element_text(size = 15),
    axis.title = element_text(size = 15)
  )


myvolcano2 <- ggplot(data = data, aes(x = logFC, y = -log10(pvalue))) +
  geom_vline(xintercept = c(-0.6, 0.6), col = "gray", linetype = 'dashed') +
  geom_hline(yintercept = -log10(0.05), col = "gray", linetype = 'dashed') +
  geom_point(aes(color = Compound_Class, shape = Sample_Type), size = 1.5, alpha = 0.8) +
  geom_text(aes(label = Molecule), size = 3, vjust = -0.5) +  # Add labels with Compound_name
  scale_color_manual(
    values = c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00", 
                "#A65628", "#F781BF"),  # Only define colors for non-NA values
    na.translate = FALSE  # Exclude NA values from the color mapping and legend
  ) +
  scale_shape_manual(
    values = c(0, 1, 2)  # Use hollow shapes for Sample_Type
  ) +
  coord_cartesian(ylim = c(0, 5), xlim = c(-15, 15)) +
  labs(color = 'Compound Type', shape = 'Significance') +
  scale_x_continuous(breaks = seq(-15, 15, 5)) +
  theme(
    plot.title = element_text(size = 15),
    axis.title = element_text(size = 15)
  )


library(svglite)

plot(myvolcano2)

ggsave(file="compound type and compound class labels 01312025.svg", plot=myvolcano2, width=11, height=8)
```

